### ISSUE TITLE
Compile issue using MSVC 2017

### ISSUE THREAD

**Issue by BastiaanOlij** [microsoft/angle#150]
Hi all,

Newbie here, trying to compile Angle for the first time (ms-master) using MSVC 2017 on a Window 10 machine. Switch the SDK to 10.0.17134.0 as it for some reason didn't want to use the older build tools and SDK even after installing (I think I installed them correctly).

It gets pretty far through building things but then errors out on the following 3 compile errors:
```
 CoreWindowNativeWindow.cpp
c:\users\basti\development\angle\src\libangle\renderer\d3d\d3d11\winrt\corewindownativewindow.cpp(212): error C4996: 'A
BI::Windows::Graphics::Display::IDisplayPropertiesStatics': DisplayProperties may be altered or unavailable for release
s after Windows Phone 8.1. Instead, use DisplayInformation. [c:\Users\basti\Development\angle\winrt\10\src\libANGLE.vcx
proj]
  c:\program files (x86)\windows kits\10\include\10.0.17134.0\winrt\windows.graphics.display.h(2453): note: see declara
  tion of 'ABI::Windows::Graphics::Display::IDisplayPropertiesStatics'
c:\users\basti\development\angle\src\libangle\renderer\d3d\d3d11\winrt\corewindownativewindow.cpp(214): error C4996: 'R
untimeClass_Windows_Graphics_Display_DisplayProperties': DisplayProperties may be altered or unavailable for releases a
fter Windows Phone 8.1. Instead, use DisplayInformation. [c:\Users\basti\Development\angle\winrt\10\src\libANGLE.vcxpro
j]
  c:\program files (x86)\windows kits\10\include\10.0.17134.0\winrt\windows.graphics.display.h(2830): note: see declara
  tion of 'RuntimeClass_Windows_Graphics_Display_DisplayProperties'
c:\users\basti\development\angle\src\libangle\renderer\d3d\d3d11\winrt\corewindownativewindow.cpp(217): error C4996: 'A
BI::Windows::Graphics::Display::IDisplayPropertiesStatics::get_LogicalDpi': DisplayProperties may be altered or unavail
able for releases after Windows Phone 8.1. Instead, use DisplayInformation. [c:\Users\basti\Development\angle\winrt\10\
src\libANGLE.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17134.0\winrt\windows.graphics.display.h(2510): note: see declara
  tion of 'ABI::Windows::Graphics::Display::IDisplayPropertiesStatics::get_LogicalDpi'
```

Looks like a few deprecated functions. I don't know if I can tell it to just ignore those or if this actually requires a change?

**Comment by stammen** [comment]
Look at pull request https://github.com/Microsoft/angle/pull/146. It has the fix for the compile errors.

**Comment by BastiaanOlij** [comment]
Thanks @stammen , I'm going to try that out this weekend, see if I can get it up and running.

**Comment by BastiaanOlij** [comment]
Ok, applying the patch for #146 solved that issues but now there is a new one...

preprocessor.lib(Macro.obj) : error LNK2001: unresolved external symbol _guard_dispatch_icall [c:\Users\basti\Developme
nt\angle\winrt\10\src\libGLESv2.vcxproj]
c:\Users\basti\Development\angle\winrt\10\src\Release_x64\libGLESv2.dll : fatal error LNK1120: 1 unresolved externals [
c:\Users\basti\Development\angle\winrt\10\src\libGLESv2.vcxproj]

**Comment by Faless** [comment]
I can confirm this issue, I'm unable to build with VS 2017, once again, upgrading MS tools seems to be bad practice...

**Comment by birsoyo** [comment]
In order to fix `_guard_dispatch_icall` unresolved external symbol error, `/guard:cf` option should be added to compiler flags as well.

Sources:
* https://github.com/Microsoft/vcpkg/pull/3718#issue-194658499
* MSDN : [The /guard:cf option must be passed to both the compiler and linker to build code that uses the CFG exploit mitigation technique](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard)

**Comment by austinkinross** [comment]
Hi, going forward we strongly recommend that you build (and use) ANGLE from the upstream ANGLE repository: https://opensource.google.com/projects/angle

I believe that this issue has already been fixed there.

Thanks
Austin
